const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  REMOVE_TOKEN: "REMOVE_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ROLES: "GET_ROLES",
  GET_SUBSCRIPTIONS: "GET_SUBSCRIPTIONS",
  GET_SUBS_USERS: "GET_SUBS_USERS",
};

export default ACTIONS;
